### ISSUE TITLE
How to convert Remember me checkbox to toggle button?

### ISSUE THREAD

**Issue by dbjpanda** [actions-pack/feedbacks#24]
<img width="266" alt="Screenshot 2020-05-17 at 11 34 12 AM" src="https://user-images.githubusercontent.com/17483092/82137110-a313ec00-9832-11ea-8b7f-0ed4af19233e.png">

```css
/* Toggle Button */
.elementor-acceptance-field {
    position: relative;
	-webkit-appearance: none;
	-webkit-tap-highlight-color: transparent;
	outline: 0;
	border: 0 !important;
	cursor: pointer;
	margin-right: 45px;
}


/* To create surface of toggle button */
.elementor-acceptance-field:after {
    position: absolute;
    top: 0;
	content: '';
	width: 38px;
	height: 19px;
	display: inline-block;
	background: rgba(196, 195, 195, 0.55);
	border-radius: 18px;
	clear: both;
}


/* Contents before checkbox to create toggle handle */
.elementor-acceptance-field:before {
    position: absolute;
	content: '';
	top: 1px;
	z-index: 1;
	width: 16px;
	height: 16px;
	display: block;
	border-radius: 50%;
	background: rgb(255, 255, 255);
	box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.6);
}


/* Shift the handle to left on check event */
.elementor-acceptance-field:checked:before {
	left: 21px;
	box-shadow: -1px 1px 3px rgba(0, 0, 0, 0.6);
}
/* Background color when toggle button will be active */
.elementor-acceptance-field:checked:after {
	background: #613892;
}

/* Transition for smoothness */
.elementor-acceptance-field,
.elementor-acceptance-field:before,
.elementor-acceptance-field:after,
.elementor-acceptance-field:checked:before,
.elementor-acceptance-field:checked:after {
	transition: ease .3s;
	-webkit-transition: ease .3s;
	-moz-transition: ease .3s;
	-o-transition: ease .3s;
	
}
```
